### ISSUE TITLE
Lua error on 16/11 WoW update 

### ISSUE THREAD

**Issue by Progghost** [kacpak/Auto-Sell-Grey-and-Repair-Equipement#14]
5x ...terface/AddOns/kSellGreyNRepair/kSellGreyNRepair.lua:24: attempt to call global 'GetContainerNumSlots' (a nil value)
[string "@Interface/AddOns/kSellGreyNRepair/kSellGreyNRepair.lua"]:24: in function <...terface/AddOns/kSellGreyNRepair/kSellGreyNRepair.lua:20>

Locals:
self = Frame {
 0 = <userdata>
}
event = "MERCHANT_SHOW"
(for index) = 0
(for limit) = 4
(for step) = 1
myBags = 0
(*temporary) = 1
(*temporary) = nil
(*temporary) = 0
(*temporary) = "attempt to call global 'GetContainerNumSlots' (a nil value)"

**Comment by Strik3ria** [comment]
Addressed in https://github.com/kacpak/Auto-Sell-Grey-and-Repair-Equipement/pull/10

**Comment by kacpak** [comment]
should be fixed
