### ISSUE TITLE
Not all greys selling

### ISSUE THREAD

**Issue by glacials** [kacpak/Auto-Sell-Grey-and-Repair-Equipement#2]
I'm running into an issue where only a small amount (< 10) greys are selling when opening a vendor window. I can work around it by closing the vendor window and opening it again until all greys are sold.

**Comment by kacpak** [comment]
I'll try to reproduce it and find a fix for that.  
Unfortunately I'll be out of WoW untill next week, so it may have to wait untill I come back.

**Comment by kacpak** [comment]
Can you check if v1.4.1 fixed this issue?
For now I consider this closed.

**Comment by glacials** [comment]
I have not noticed the issue happening since then, thanks for your help!
