### ISSUE TITLE
Feature request: Guild cost shown

### ISSUE THREAD

**Issue by Gingergod5** [kacpak/Auto-Sell-Grey-and-Repair-Equipement#4]
hello,

love the addon and the fact its simple.

would it be possible to show the cost of the repair when its done through guild?

Thanks,

p.s. Apologies if this isn't in the right location, i couldn't see requests :)

**Comment by kacpak** [comment]
Yes, it's the right location.
I plan on adding proper configuration for this addon with basic options while still keeping current default behaviour.
So I can plan to add this to, though it's hard to say when, since lately I'm preoccupied with other stuff.
