### ISSUE TITLE
AutoQuest functions pls

### ISSUE THREAD

**Issue by Drui7** [kacpak/Auto-Sell-Grey-and-Repair-Equipement#6]
0. If in the dialog box of the mob there is a "yellow" (completed) task, then enter it
1. If there is a "continue" button in the mob's dialog box, then click it
2. If there is a "accept" button in the mob's dialog box, then click it
3. If there is a "complete" button in the mob's dialog box and there is no reward, or just 1 thing to choose from, then click it
4. If there is a "complete" button in the mob's dialog box and a few things to choose from, then select the most expensive (if everything costs 0, then choose any) thing, but DO NOT click "complete"

You do not need to open automatically tasks that have not been accepted yet, you do not need to open tasks that are not completed. No need to take the "blue" (completed and at the same endless / repeatable tasks).

**Comment by kacpak** [comment]
Sorry, I'm not willing to implement that. This addon's purpose is to provide only what's in the name with minimal (or no) configuration needed.
I'm sure there are already addons like that though.

**Comment by Drui7** [comment]
Such additions are too heavy in customization =( I didn’t find a simple one to do only that which would simplify the gameplay and not harm the character
