### ISSUE TITLE
Guild Repair on/off option

### ISSUE THREAD

**Issue by sarahjanesmith25** [kacpak/Auto-Sell-Grey-and-Repair-Equipement#9]
Is there any way to not automatically use guild resources to repair, and option to choose which is used first etc? Guild funds are situational and not appropriate 100% of the time.

Thanks in advance

**Comment by Strik3ria** [comment]
https://github.com/kacpak/Auto-Sell-Grey-and-Repair-Equipement/pull/12 May be better to resolve this issue, using issue 1 to track adding a settings area.

**Comment by kacpak** [comment]
Duplicate of #1
